// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WADapi.Data;

#nullable disable

namespace officecallendar.backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121093431_UpdateMessagesWithVisible")]
    partial class UpdateMessagesWithVisible
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Officecalendar.Backend.Models.Attendance", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("username");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.Event", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("booking_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("creator_username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("end_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("last_edited_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("creator_username");

                    b.HasIndex("username");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.EventSubscription", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("event_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("participated")
                        .HasColumnType("bit");

                    b.HasKey("username", "event_id");

                    b.HasIndex("event_id");

                    b.ToTable("EventSubscriptions");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.Group", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.GroupMembership", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("group_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("username", "group_id");

                    b.HasIndex("group_id");

                    b.ToTable("GroupMemberships");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.Message", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("creation_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("last_edited_date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("referenced_event_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("sender_username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("visible")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("referenced_event_id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.MessageReceiver", b =>
                {
                    b.Property<Guid>("message_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("message_id", "username");

                    b.HasIndex("username");

                    b.ToTable("MessageReceivers");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.Review", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("event_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("stars")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("event_id");

                    b.HasIndex("username");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.Room", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("available")
                        .HasColumnType("bit");

                    b.Property<int?>("capacity")
                        .HasColumnType("int");

                    b.Property<string>("room_location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.RoomBooking", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Roomid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("booked_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("end_time")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("event_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("room_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("Roomid");

                    b.HasIndex("booked_by");

                    b.HasIndex("event_id");

                    b.ToTable("RoomBookings");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.RoomBookingRoom", b =>
                {
                    b.Property<Guid>("booking_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("room_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("booking_id", "room_id");

                    b.HasIndex("room_id");

                    b.ToTable("RoomBookingRoom");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.User", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("creation_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.Attendance", b =>
                {
                    b.HasOne("Officecalendar.Backend.Models.User", "User")
                        .WithMany("Attendances")
                        .HasForeignKey("username")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.Event", b =>
                {
                    b.HasOne("Officecalendar.Backend.Models.User", "Creator")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("creator_username")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Officecalendar.Backend.Models.User", null)
                        .WithMany("Events")
                        .HasForeignKey("username");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.EventSubscription", b =>
                {
                    b.HasOne("Officecalendar.Backend.Models.Event", "Event")
                        .WithMany("EventSubscriptions")
                        .HasForeignKey("event_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Officecalendar.Backend.Models.User", "User")
                        .WithMany("EventSubscriptions")
                        .HasForeignKey("username")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.GroupMembership", b =>
                {
                    b.HasOne("Officecalendar.Backend.Models.Group", "Group")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Officecalendar.Backend.Models.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("username")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.Message", b =>
                {
                    b.HasOne("Officecalendar.Backend.Models.Event", "Event")
                        .WithMany("Messages")
                        .HasForeignKey("referenced_event_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.MessageReceiver", b =>
                {
                    b.HasOne("Officecalendar.Backend.Models.Message", "Message")
                        .WithMany("MessageReceivers")
                        .HasForeignKey("message_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Officecalendar.Backend.Models.User", "User")
                        .WithMany("MessageReceivers")
                        .HasForeignKey("username")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.Review", b =>
                {
                    b.HasOne("Officecalendar.Backend.Models.Event", "Event")
                        .WithMany("Reviews")
                        .HasForeignKey("event_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Officecalendar.Backend.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("username")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.RoomBooking", b =>
                {
                    b.HasOne("Officecalendar.Backend.Models.Room", "Room")
                        .WithMany("RoomBookings")
                        .HasForeignKey("Roomid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Officecalendar.Backend.Models.User", "User")
                        .WithMany("RoomBookings")
                        .HasForeignKey("booked_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Officecalendar.Backend.Models.Event", "Event")
                        .WithMany("RoomBookings")
                        .HasForeignKey("event_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.RoomBookingRoom", b =>
                {
                    b.HasOne("Officecalendar.Backend.Models.RoomBooking", "RoomBooking")
                        .WithMany("RoomBookingRooms")
                        .HasForeignKey("booking_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Officecalendar.Backend.Models.Room", "Room")
                        .WithMany("RoomBookingRooms")
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("RoomBooking");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.Event", b =>
                {
                    b.Navigation("EventSubscriptions");

                    b.Navigation("Messages");

                    b.Navigation("Reviews");

                    b.Navigation("RoomBookings");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.Group", b =>
                {
                    b.Navigation("GroupMemberships");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.Message", b =>
                {
                    b.Navigation("MessageReceivers");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.Room", b =>
                {
                    b.Navigation("RoomBookingRooms");

                    b.Navigation("RoomBookings");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.RoomBooking", b =>
                {
                    b.Navigation("RoomBookingRooms");
                });

            modelBuilder.Entity("Officecalendar.Backend.Models.User", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("CreatedEvents");

                    b.Navigation("EventSubscriptions");

                    b.Navigation("Events");

                    b.Navigation("GroupMemberships");

                    b.Navigation("MessageReceivers");

                    b.Navigation("Reviews");

                    b.Navigation("RoomBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
